local utils = require("utils")

utils.buf_keymap("n", "<leader>for", ":lua vim.lsp.buf.formatting()<CR>")
utils.buf_keymap("n", "<leader>dec", ":lua vim.lsp.buf.declaration()<CR>")
utils.buf_keymap("n", "<leader>def", ":lua vim.lsp.buf.definition()<CR>")
utils.buf_keymap("n", "<leader>hov", ":lua vim.lsp.buf.hover()<CR>")
utils.buf_keymap("n", "<leader>imp", ":lua vim.lsp.buf.implementation()<CR>")
utils.buf_keymap("n", "<leader>sig", ":lua vim.lsp.buf.signature_help()<CR>")
utils.buf_keymap("n", "<leader>typ", ":lua vim.lsp.buf.type_definition()<CR>")
utils.buf_keymap("n", "<leader>ren", ":lua vim.lsp.buf.rename()<CR>")
utils.buf_keymap("n", "<leader>cod", ":lua vim.lsp.buf.code_action()<CR>")
utils.buf_keymap("n", "<leader>ref", ":lua vim.lsp.buf.references()<CR>")
utils.buf_keymap("n", "<leader>dia", ":lua vim.diagnostic.open_float()<CR>")
utils.buf_keymap("n", "<leader>[[", ":lua vim.lsp.diagnostic.goto_prev()<CR>")
utils.buf_keymap("n", "<leader>]]", ":lua vim.lsp.diagnostic.goto_next()<CR>")
