#!/bin/zsh

local brightness=${(j:.:)${(s::)${(l:2::0:)${1:-10}}}}
osascript << EOS
if application "System Preferences" is running then
    try
        tell application "System Preferences" to quit
    on error
        do shell script "killall 'System Preferences'"
    end try
end if

repeat while application "System Preferences" is running
    delay 0.1
end repeat

tell application "System Preferences" to reveal anchor "displaysDisplayTab" of ¬
    pane id "com.apple.preference.displays"

tell application "System Events" to ¬
    tell value indicator 1 of slider 1 of tab group 1 of window 1 of ¬
        application process "System Preferences" to set its value to $brightness

quit application "System Preferences"
EOS
