#!/bin/zsh

for target_file in `builtin cd $DOTFILES && fd -t f | sed 's/^.\///' | fzf --preview 'bat {}'`; do
    local target_fullpath=$DOTFILES/$target_file
    local target_type=${${${target_fullpath#$PERSONAL/}#$DOTFILES/}%%/*}
    [ -f $target_fullpath ] && ( vim "$target_fullpath"; setup $target_type)
done
[ ! -z $target_file ] && relogin

