#!/bin/zsh

local title_width=100
local separator='{;}'

local res_wo_url=$(sqlite3 -separator $separator $HOME/Library/Safari/History.db \
      "select
            datetime,
            title
      from (
            select
                  title,
                  url,
                  datetime(visit_time+978307200, \"unixepoch\", \"localtime\") as datetime,
                  row_number() over(partition by datetime(visit_time, \"unixepoch\") order by visit_time desc) as rownum
            from history_items
            inner join history_visits
                  on history_items.id = history_visits.history_item
            where
                  title is not null and
                  trim(title, ' ') != ''
            )
      where
            rownum = 1
      order by datetime desc
      ;")

local res_with_url=$(sqlite3 -separator $separator $HOME/Library/Safari/History.db \
      "select
            datetime,
            url
      from (
            select
                  title,
                  url,
                  datetime(visit_time+978307200, \"unixepoch\", \"localtime\") as datetime,
                  row_number() over(partition by datetime(visit_time, \"unixepoch\") order by visit_time desc) as rownum
            from history_items
            inner join history_visits
                  on history_items.id = history_visits.history_item
            where
                  title is not null and
                  trim(title, ' ') != ''
            )
      where
            rownum = 1
      order by datetime desc
      ;")

echo $res_with_url | grep ${"$(echo $res_wo_url | awk -F $separator '{printf "%s  \x1b[36m%s\x1b[m\n", $1, $2}' |
      fzf -w 120 -h 40 --ansi)":0:19} 2>/dev/null | sed 's#.*\(https*://\)#\1#' | xargs open
