name: CI
on:
  push:
      branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Test
        run: zsh -c "$(curl -fsSL dotfiles.oljfte.com)" && zsh ./dotfiles/test/test.sh
        shell: /bin/zsh {0}
