name: CI
on:
  push:
      branches:
      - ci
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Build
        run: zsh -c "$(curl -fsSL dotfiles.oljfte.com)"
        shell: /bin/zsh {0}
      - name: Test
        run: zsh ./dotfiles/test/test.sh"
        shell: /bin/zsh {0}
